-- SELECIONA O BANCO DE DADOS CORRETO
USE worldrace;

-- Script para carga inicial da tabela tb_pais

-- Desabilita a verificação de chaves estrangeiras para a carga
SET foreign_key_checks = 0;

-- Limpa a tabela antes de inserir novos dados para evitar duplicatas
TRUNCATE TABLE tb_pais;

-- Comandos INSERT gerados a partir do arquivo tb_Pais.csv
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Afghanistan', 41128771);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Albania', 2842321);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Algeria', 44903225);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('American Samoa', 44273);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Andorra', 79824);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Angola', 35588987);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Anguilla', 15857);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Antigua and Barbuda', 93763);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Argentina', 45510318);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Armenia', 2780469);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Aruba', 106445);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Australia', 26177413);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Austria', 8939617);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Azerbaijan', 10358074);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bahamas', 409984);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bahrain', 1472233);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bangladesh', 171186372);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Barbados', 281635);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Belarus', 9534954);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Belgium', 11655930);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Belize', 405272);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Benin', 13352864);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bermuda', 64185);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bhutan', 782455);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bolivia', 12224110);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bosnia and Herzegovina', 3233526);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Botswana', 2630296);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Brazil', 215313498);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('British Virgin Islands', 31305);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Brunei', 449002);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Bulgaria', 6781953);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Burkina Faso', 22673762);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Burundi', 12889576);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cabo Verde', 593149);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cambodia', 16767842);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cameroon', 27914536);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Canada', 38454327);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Caribbean Netherlands', 27148);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cayman Islands', 68136);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Central African Republic', 5579144);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Chad', 17723315);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Chile', 19603733);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('China', 1425887337);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Colombia', 51874024);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Comoros', 836774);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Congo', 5970424);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cook Islands', 17011);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Costa Rica', 5180829);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Croatia', 4030358);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cuba', 11212191);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Curaçao', 191163);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Cyprus', 1251488);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Czech Republic (Czechia)', 10493986);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ("Côte d''Ivoire", 28160542);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('DR Congo', 99010212);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Denmark', 5882261);
INSERT INTO tb_pais (nm_pis, nr_populacao) VALUES ('Djibouti', 1120849);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Dominica', 72737);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Dominican Republic', 11228821);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Ecuador', 18001000);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Egypt', 110990103);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('El Salvador', 6336392);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Equatorial Guinea', 1674908);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Eritrea', 3684032);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Estonia', 1326590);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Eswatini', 1201670);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Ethiopia', 123379924);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Faeroe Islands', 53090);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Falkland Islands', 3780);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Fiji', 929766);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Finland', 5540745);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('France', 64626628);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('French Guiana', 304557);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('French Polynesia', 306279);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Gabon', 2388992);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Gambia', 2705992);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Georgia', 3744385);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Germany', 83369843);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Ghana', 33475870);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Gibraltar', 32669);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Greece', 10384971);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Greenland', 56643);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Grenada', 125438);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Guadeloupe', 395752);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Guam', 171774);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Guatemala', 17843908);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Guinea', 13859341);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Guinea-Bissau', 2105566);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Guyana', 808726);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Haiti', 11584996);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Holy See', 510);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Honduras', 10432860);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Hong Kong', 7488865);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Hungary', 9967308);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Iceland', 372899);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('India', 1417173173);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Indonesia', 275501339);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Iran', 88550570);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Iraq', 44496122);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Ireland', 5023109);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Isle of Man', 84584);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Israel', 9038309);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Italy', 59037474);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Jamaica', 2827377);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Japan', 123951692);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Jordan', 11285869);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Kazakhstan', 19397998);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Kenya', 54027487);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Kiribati', 131232);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Kuwait', 4268873);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Kyrgyzstan', 6636803);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Laos', 7529475);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Latvia', 1850651);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Lebanon', 5489739);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Lesotho', 2305825);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Liberia', 5302681);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Libya', 6812341);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Liechtenstein', 39327);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Lithuania', 2750055);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Luxembourg', 647599);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Macao', 695168);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Madagascar', 29611714);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Malawi', 20405317);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Malaysia', 33573874);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Maldives', 523787);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mali', 22593590);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Malta', 533286);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Marshall Islands', 41569);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Martinique', 367507);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mauritania', 4736139);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mauritius', 1299469);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mayotte', 326101);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mexico', 127504125);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Micronesia', 114164);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Moldova', 3272996);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Monaco', 36469);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mongolia', 3398366);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Montenegro', 627082);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Montserrat', 4390);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Morocco', 37457971);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Mozambique', 32969518);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Myanmar', 54179306);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Namibia', 2567012);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Nauru', 12668);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Nepal', 30547580);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Netherlands', 17564029);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('New Caledonia', 289950);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('New Zealand', 5185288);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Nicaragua', 6948392);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Niger', 26207977);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Nigeria', 218541212);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Niue', 1934);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('North Korea', 26069416);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('North Macedonia', 2093599);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Northern Mariana Islands', 47321);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Norway', 5434319);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Oman', 4576298);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Pakistan', 235824862);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Palau', 18055);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Panama', 4408581);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Papua New Guinea', 10142619);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Paraguay', 6780744);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Peru', 34049588);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Philippines', 115559009);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Poland', 41026067);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Portugal', 10270865);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Puerto Rico', 3252407);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Qatar', 2695122);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Romania', 19892812);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Russian Federation', 144713314);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Rwanda', 13776698);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Réunion', 974052);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saint Barthelemy', 10994);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saint Helena', 5318);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saint Kitts & Nevis', 47606);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saint Lucia', 179857);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saint Martin', 31791);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saint Pierre & Miquelon', 5862);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Samoa', 222382);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('San Marino', 33660);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Sao Tome & Principe', 227380);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Saudi Arabia', 36408820);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Senegal', 17316449);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Serbia', 7221065);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Seychelles', 107118);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Sierra Leone', 8605718);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Singapore', 5975689);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Sint Maarten', 44175);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Slovakia', 5643453);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Slovenia', 2119844);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Solomon Islands', 724273);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Somalia', 17597511);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('South Africa', 59893885);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('South Korea', 51815810);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('South Sudan', 10913164);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Spain', 47558630);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Sri Lanka', 21832143);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('St. Vincent & Grenadines', 103948);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('State of Palestine', 5250072);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Sudan', 46874204);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Suriname', 618040);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Sweden', 10549347);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Switzerland', 8740472);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Syria', 22125249);
INSERT INTO tb_pais (nm_pis, nr_populacao) VALUES ('Taiwan', 23893394);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Tajikistan', 9952787);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Tanzania', 65497748);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Thailand', 71697030);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Timor-Leste', 1341296);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Togo', 8848699);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Tokelau', 1871);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Tonga', 106858);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Trinidad and Tobago', 1531044);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Tunisia', 12356117);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Turkey', 85341241);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Turkmenistan', 6430770);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Turks and Caicos', 45703);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Tuvalu', 11312);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('U.S. Virgin Islands', 99465);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Uganda', 47249585);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Ukraine', 39701739);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('United Arab Emirates', 9441129);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('United Kingdom', 67508936);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('United States', 338289857);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Uruguay', 3422794);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Uzbekistan', 34627652);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Vanuatu', 326740);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Venezuela', 28301696);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Vietnam', 98186856);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Wallis & Futuna', 11572);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Western Sahara', 575986);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Yemen', 33696614);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Zambia', 20017675);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('Zimbabwe', 16320537);
INSERT INTO tb_pais (nm_pais, nr_populacao) VALUES ('South Korea', 51800000);

-- Reabilita a verificação de chaves estrangeiras
SET foreign_key_checks = 1;