-- Script para carga da tabela tb_equipe
USE worldrace;

-- Desabilita a verificação de chaves estrangeiras para a carga
SET foreign_key_checks = 0;

-- Limpa a tabela antes de inserir novos dados
TRUNCATE TABLE tb_equipe;

-- Comandos INSERT para a tabela tb_equipe
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('BMW Sauber', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Renault', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toro Rosso', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Ferrari', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toyota', 27);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Super Aguri', 27);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Honda', 27);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Spyker', 36);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('MF1', 43);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Spyker MF1', 36);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Jordan', 44);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('BAR', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Prost', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Arrows', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Benetton', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Jaguar', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Stewart', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Tyrrell', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Lola', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Ligier', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Forti', 29);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Footwork', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Pacific', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Simtek', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Larrousse', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Lotus', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('March', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Brabham', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Fondmetal', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Andrea Moda', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Dallara', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('AGS', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Lambo', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Coloni', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Osella', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('EuroBrun', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Onyx', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Leyton House', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Life', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Rial', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Zakspeed', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('RAM', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Spirit', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toleman', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('ATS', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Theodore', 45);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Fittipaldi', 29);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Ensign', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Shadow', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Wolf', 19);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Surtees', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Hesketh', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Penske', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Boro', 36);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Parnelli', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Kojima', 27);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('BRM', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('LEC', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McGuire', 13);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Matra', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Trojan', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Amon', 46);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Token', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Lyncar', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Maki', 27);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Embassy Hill', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper-Climax', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Greifzu', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Gordini', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Frazer Nash', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Veritas', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('OSCA', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Connaught', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Alta', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('HWM', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Maserati', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('ERA', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cisitalia', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Simca', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Talbot-Lago', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('AFM', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper-Maserati', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper-Bristol', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('BMW', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Vanwall', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Epperly', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Kurtis Kraft', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Kuzma', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Watson', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Scarab', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Porsche', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('De Tomaso', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Ferguson', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Gilby', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Stebro', 19);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Scirocco', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Derrington', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Eagle-Climax', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Eagle-Weslake', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('LDS', 33);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Protos', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Shannon', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Bellasi', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Politoys', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Connew', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Tecno', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Iso Marlboro', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Brawn', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Force India', 41);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Mercedes', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Virgin', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('HRT', 16);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Caterham', 14);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Marussia', 43);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Lotus F1', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Haas F1 Team', 42);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Manor Marussia', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Racing Point', 19);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('AlphaTauri', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Alpine F1 Team', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Aston Martin', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Alfa Romeo', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Kick Sauber', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('RB F1 Team', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Eifelland', 22);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Alfa Romeo-Sauber', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('De Tomaso-Alfa Romeo', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper-OSCA', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('MBM', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper-Borgward', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Cooper-Ford', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Aston Martin-Aston Martin', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Aston Martin-Mercedes', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('JBW', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Emeryson', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('ENB', 24);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('De Tomaso-Osca', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('De Tomaso-Ferrari', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('De Tomaso-Cosworth', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('De Tomaso-Ford', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Toyota', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Mercedes', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Renault', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Cosworth', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-BMW', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Mecachrome', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Supertec', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Judd', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Honda', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Williams-Ford', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Alfa Romeo-Ferrari', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toro Rosso-Ferrari', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toro Rosso-Renault', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toro Rosso-Honda', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Toro Rosso-Cosworth', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Super Aguri-Honda', 27);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Spyker-Ferrari', 36);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber-Petronas', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber-Mercedes', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber-Ilmor', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber-Ford', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber-Ferrari', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Sauber-BMW Sauber', 40);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Renault-Renault', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Renault-Mecachrome', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Renault-Playlife', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull-TAG Heuer', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull-Renault', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull-RBPT', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull-Honda', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull-Ferrari', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Red Bull-Cosworth', 38);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Prost-Peugeot', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Prost-Mugen-Honda', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Prost-Ferrari', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Prost-Acer', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Ford', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-BRM', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Climax', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Pratt & Whitney', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Maserati', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Cosworth', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Renault', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Judd', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Lamborghini', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Team Lotus-Mugen-Honda', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Pacific-Ford', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Pacific-Ilmor', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-Motori Moderni', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-Lamborghini', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-Hart', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-Ford', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-European', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-Cosworth', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Minardi-Fondmetal', 25);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Midland-Toyota', 43);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Mercedes', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-TAG', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Serenissima', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Renault', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Peugeot', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Honda', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Ford', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-BRM', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('McLaren-Alfa Romeo', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('March-Judd', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('March-Ilmor', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('March-Ford', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('March-Alfa Romeo', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Manor-Cosworth', 21);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Ligier-Peugeot', 20);
INSERT INTO tb_equipe (nm_equipe, tb_Pais_idpais) VALUES ('Ligier-Mugen-Honda', 20);

-- Reabilita a verificação de chaves estrangeiras
SET foreign_key_checks = 1;